language: go

go:
    - 1.16.x

script: make dist

deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
        tags: true
