name: build tar files and publish to releases

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build tar files and release to releases
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: checkout repo
      uses: actions/checkout@v2

    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v1

    - name: read version file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"

    - name: Build tar files
      run: make dist

    - name: create the release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        tag_name: ${{ steps.getversion.outputs.version }}+${{ github.run_number }}
        body: ${{ steps.extract-release-notes.outputs.release_notes }}
        files: ./dist/*.tar.gz
        fail_on_unmatched_files: true
